- name: sync source
  git:
    repo: https://github.com/qiime2/library
    dest: /home/ubuntu/library-src
    version: master
    update: true
    force: true

- name: template in docker-compose vars
  no_log: true
  template:
    src: "{{ item }}"
    dest: "/home/ubuntu/library-src/{{ item }}"
  with_items:
    - docker-compose.yml

- name: start containers
  become: true
  no_log: true
  command: docker-compose -f /home/ubuntu/library-src/docker-compose.yml up -d --build --remove-orphans
  register: dc
  changed_when: '"Creating library-worker_1" in dc.stderr'
